[package]
name = "relm4-tic-tac-toe"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
relm4 = { version = "0.6.1", default-features = false, features = ["macros", "gnome_42"] }
relm4-components = "0.6.1"
serde = { version = "1", features = ["derive", "default"] }
serde_json = "1"